version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - postgres_db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  web:
    stdin_open: true
    tty: true
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/share-video
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  postgres_db:
